/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

public partial class emsg_inf_push {
  /// <summary>
  /// 入口函数
  /// </summary>
  public interface Iface {
    string process(string licence, string sn, string content);
    #if SILVERLIGHT
    IAsyncResult Begin_process(AsyncCallback callback, object state, string licence, string sn, string content);
    string End_process(IAsyncResult asyncResult);
    #endif
    string process_batch(string licence, string sn, List<string> contents);
    #if SILVERLIGHT
    IAsyncResult Begin_process_batch(AsyncCallback callback, object state, string licence, string sn, List<string> contents);
    string End_process_batch(IAsyncResult asyncResult);
    #endif
  }

  /// <summary>
  /// 入口函数
  /// </summary>
  public class Client : IDisposable, Iface {
    public Client(TProtocol prot) : this(prot, prot)
    {
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      iprot_ = iprot;
      oprot_ = oprot;
    }

    protected TProtocol iprot_;
    protected TProtocol oprot_;
    protected int seqid_;

    public TProtocol InputProtocol
    {
      get { return iprot_; }
    }
    public TProtocol OutputProtocol
    {
      get { return oprot_; }
    }


    #region " IDisposable Support "
    private bool _IsDisposed;

    // IDisposable
    public void Dispose()
    {
      Dispose(true);
    }
    

    protected virtual void Dispose(bool disposing)
    {
      if (!_IsDisposed)
      {
        if (disposing)
        {
          if (iprot_ != null)
          {
            ((IDisposable)iprot_).Dispose();
          }
          if (oprot_ != null)
          {
            ((IDisposable)oprot_).Dispose();
          }
        }
      }
      _IsDisposed = true;
    }
    #endregion


    
    #if SILVERLIGHT
    public IAsyncResult Begin_process(AsyncCallback callback, object state, string licence, string sn, string content)
    {
      return send_process(callback, state, licence, sn, content);
    }

    public string End_process(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_process();
    }

    #endif

    public string process(string licence, string sn, string content)
    {
      #if !SILVERLIGHT
      send_process(licence, sn, content);
      return recv_process();

      #else
      var asyncResult = Begin_process(null, null, licence, sn, content);
      return End_process(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_process(AsyncCallback callback, object state, string licence, string sn, string content)
    #else
    public void send_process(string licence, string sn, string content)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("process", TMessageType.Call, seqid_));
      process_args args = new process_args();
      args.Licence = licence;
      args.Sn = sn;
      args.Content = content;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public string recv_process()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      process_result result = new process_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "process failed: unknown result");
    }

    
    #if SILVERLIGHT
    public IAsyncResult Begin_process_batch(AsyncCallback callback, object state, string licence, string sn, List<string> contents)
    {
      return send_process_batch(callback, state, licence, sn, contents);
    }

    public string End_process_batch(IAsyncResult asyncResult)
    {
      oprot_.Transport.EndFlush(asyncResult);
      return recv_process_batch();
    }

    #endif

    public string process_batch(string licence, string sn, List<string> contents)
    {
      #if !SILVERLIGHT
      send_process_batch(licence, sn, contents);
      return recv_process_batch();

      #else
      var asyncResult = Begin_process_batch(null, null, licence, sn, contents);
      return End_process_batch(asyncResult);

      #endif
    }
    #if SILVERLIGHT
    public IAsyncResult send_process_batch(AsyncCallback callback, object state, string licence, string sn, List<string> contents)
    #else
    public void send_process_batch(string licence, string sn, List<string> contents)
    #endif
    {
      oprot_.WriteMessageBegin(new TMessage("process_batch", TMessageType.Call, seqid_));
      process_batch_args args = new process_batch_args();
      args.Licence = licence;
      args.Sn = sn;
      args.Contents = contents;
      args.Write(oprot_);
      oprot_.WriteMessageEnd();
      #if SILVERLIGHT
      return oprot_.Transport.BeginFlush(callback, state);
      #else
      oprot_.Transport.Flush();
      #endif
    }

    public string recv_process_batch()
    {
      TMessage msg = iprot_.ReadMessageBegin();
      if (msg.Type == TMessageType.Exception) {
        TApplicationException x = TApplicationException.Read(iprot_);
        iprot_.ReadMessageEnd();
        throw x;
      }
      process_batch_result result = new process_batch_result();
      result.Read(iprot_);
      iprot_.ReadMessageEnd();
      if (result.__isset.success) {
        return result.Success;
      }
      throw new TApplicationException(TApplicationException.ExceptionType.MissingResult, "process_batch failed: unknown result");
    }

  }
  public class Processor : TProcessor {
    public Processor(Iface iface)
    {
      iface_ = iface;
      processMap_["process"] = process_Process;
      processMap_["process_batch"] = process_batch_Process;
    }

    protected delegate void ProcessFunction(int seqid, TProtocol iprot, TProtocol oprot);
    private Iface iface_;
    protected Dictionary<string, ProcessFunction> processMap_ = new Dictionary<string, ProcessFunction>();

    public bool Process(TProtocol iprot, TProtocol oprot)
    {
      try
      {
        TMessage msg = iprot.ReadMessageBegin();
        ProcessFunction fn;
        processMap_.TryGetValue(msg.Name, out fn);
        if (fn == null) {
          TProtocolUtil.Skip(iprot, TType.Struct);
          iprot.ReadMessageEnd();
          TApplicationException x = new TApplicationException (TApplicationException.ExceptionType.UnknownMethod, "Invalid method name: '" + msg.Name + "'");
          oprot.WriteMessageBegin(new TMessage(msg.Name, TMessageType.Exception, msg.SeqID));
          x.Write(oprot);
          oprot.WriteMessageEnd();
          oprot.Transport.Flush();
          return true;
        }
        fn(msg.SeqID, iprot, oprot);
      }
      catch (IOException)
      {
        return false;
      }
      return true;
    }

    public void process_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      process_args args = new process_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      process_result result = new process_result();
      result.Success = iface_.process(args.Licence, args.Sn, args.Content);
      oprot.WriteMessageBegin(new TMessage("process", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

    public void process_batch_Process(int seqid, TProtocol iprot, TProtocol oprot)
    {
      process_batch_args args = new process_batch_args();
      args.Read(iprot);
      iprot.ReadMessageEnd();
      process_batch_result result = new process_batch_result();
      result.Success = iface_.process_batch(args.Licence, args.Sn, args.Contents);
      oprot.WriteMessageBegin(new TMessage("process_batch", TMessageType.Reply, seqid)); 
      result.Write(oprot);
      oprot.WriteMessageEnd();
      oprot.Transport.Flush();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class process_args : TBase
  {
    private string _licence;
    private string _sn;
    private string _content;

    public string Licence
    {
      get
      {
        return _licence;
      }
      set
      {
        __isset.licence = true;
        this._licence = value;
      }
    }

    public string Sn
    {
      get
      {
        return _sn;
      }
      set
      {
        __isset.sn = true;
        this._sn = value;
      }
    }

    public string Content
    {
      get
      {
        return _content;
      }
      set
      {
        __isset.content = true;
        this._content = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool licence;
      public bool sn;
      public bool content;
    }

    public process_args() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Licence = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Sn = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Content = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("process_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Licence != null && __isset.licence) {
          field.Name = "licence";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Licence);
          oprot.WriteFieldEnd();
        }
        if (Sn != null && __isset.sn) {
          field.Name = "sn";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Sn);
          oprot.WriteFieldEnd();
        }
        if (Content != null && __isset.content) {
          field.Name = "content";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Content);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("process_args(");
      bool __first = true;
      if (Licence != null && __isset.licence) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Licence: ");
        __sb.Append(Licence);
      }
      if (Sn != null && __isset.sn) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Sn: ");
        __sb.Append(Sn);
      }
      if (Content != null && __isset.content) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Content: ");
        __sb.Append(Content);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class process_result : TBase
  {
    private string _success;

    public string Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public process_result() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.String) {
                Success = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("process_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.String;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            oprot.WriteString(Success);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("process_result(");
      bool __first = true;
      if (Success != null && __isset.success) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Success: ");
        __sb.Append(Success);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class process_batch_args : TBase
  {
    private string _licence;
    private string _sn;
    private List<string> _contents;

    public string Licence
    {
      get
      {
        return _licence;
      }
      set
      {
        __isset.licence = true;
        this._licence = value;
      }
    }

    public string Sn
    {
      get
      {
        return _sn;
      }
      set
      {
        __isset.sn = true;
        this._sn = value;
      }
    }

    public List<string> Contents
    {
      get
      {
        return _contents;
      }
      set
      {
        __isset.contents = true;
        this._contents = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool licence;
      public bool sn;
      public bool contents;
    }

    public process_batch_args() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Licence = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Sn = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.List) {
                {
                  Contents = new List<string>();
                  TList _list0 = iprot.ReadListBegin();
                  for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                  {
                    string _elem2;
                    _elem2 = iprot.ReadString();
                    Contents.Add(_elem2);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("process_batch_args");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Licence != null && __isset.licence) {
          field.Name = "licence";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Licence);
          oprot.WriteFieldEnd();
        }
        if (Sn != null && __isset.sn) {
          field.Name = "sn";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Sn);
          oprot.WriteFieldEnd();
        }
        if (Contents != null && __isset.contents) {
          field.Name = "contents";
          field.Type = TType.List;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, Contents.Count));
            foreach (string _iter3 in Contents)
            {
              oprot.WriteString(_iter3);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("process_batch_args(");
      bool __first = true;
      if (Licence != null && __isset.licence) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Licence: ");
        __sb.Append(Licence);
      }
      if (Sn != null && __isset.sn) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Sn: ");
        __sb.Append(Sn);
      }
      if (Contents != null && __isset.contents) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Contents: ");
        __sb.Append(Contents);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }


  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class process_batch_result : TBase
  {
    private string _success;

    public string Success
    {
      get
      {
        return _success;
      }
      set
      {
        __isset.success = true;
        this._success = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool success;
    }

    public process_batch_result() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 0:
              if (field.Type == TType.String) {
                Success = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("process_batch_result");
        oprot.WriteStructBegin(struc);
        TField field = new TField();

        if (this.__isset.success) {
          if (Success != null) {
            field.Name = "Success";
            field.Type = TType.String;
            field.ID = 0;
            oprot.WriteFieldBegin(field);
            oprot.WriteString(Success);
            oprot.WriteFieldEnd();
          }
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("process_batch_result(");
      bool __first = true;
      if (Success != null && __isset.success) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Success: ");
        __sb.Append(Success);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
